version: "3.0"
services:
  repo:
    build:
      context: repository
      dockerfile: Dockerfile
    image: "scrap-repo"
    depends_on:
      - mongo
    links:
      - mongo
  scrap:
    image: "scrap-main"
    build:
      context: scrapper
      dockerfile: Dockerfile
    ports:
    - 8362:8362
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
