version: "3.9"
services:
  repo:
    build: 
    ports:
      - "5000:5000"
    image: "scrap-repo"
  scrap:
    image: "scrap-main"

  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
